In [183]:
from bpemb import BPEmb
bpe = BPEmb(lang='bn',vs=200000)

In [494]:
bpe.encode_ids_with_eos(sent)

[1524, 3197, 834, 3918, 1849, 2]

In [211]:
bpe.decode_ids([1, 1524, 3197, 834, 3918, 1849, 2])

'আজ আমার মন ভালো নেই'

In [582]:
bpe.encode_ids('p')

[207]

In [209]:
sent = "আজ আমার মন ভালো নেই"
bpe.encode_ids(sent)

[1524, 3197, 834, 3918, 1849]

In [1]:
import os, numpy as np
os.getcwd()

'/home/ansari/codes/spellchecker/bart/codes'

# Finding the config of bart-large-cnn

In [457]:
import json
with open("config.json") as f:
    a = json.load(f)
a

{'_name_or_path': 'facebook/bart-large-cnn',
 '_num_labels': 3,
 'activation_dropout': 0.0,
 'activation_function': 'gelu',
 'add_final_layer_norm': False,
 'architectures': ['BartForConditionalGeneration'],
 'attention_dropout': 0.0,
 'bos_token_id': 0,
 'classif_dropout': 0.0,
 'classifier_dropout': 0.0,
 'd_model': 1024,
 'decoder_attention_heads': 16,
 'decoder_ffn_dim': 4096,
 'decoder_layerdrop': 0.0,
 'decoder_layers': 12,
 'decoder_start_token_id': 2,
 'dropout': 0.1,
 'early_stopping': True,
 'encoder_attention_heads': 16,
 'encoder_ffn_dim': 4096,
 'encoder_layerdrop': 0.0,
 'encoder_layers': 12,
 'eos_token_id': 2,
 'force_bos_token_to_be_generated': True,
 'forced_bos_token_id': 0,
 'forced_eos_token_id': 2,
 'gradient_checkpointing': False,
 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1', '2': 'LABEL_2'},
 'init_std': 0.02,
 'is_encoder_decoder': True,
 'label2id': {'LABEL_0': 0, 'LABEL_1': 1, 'LABEL_2': 2},
 'length_penalty': 2.0,
 'max_length': 142,
 'max_position_embedding

In [469]:
# config = BartConfig(a)
# config = model.config
# model.config.save_pretrained("bart.config")
config = BartConfig.from_pretrained("bart.config")

In [477]:
config.vocab_size

23

In [470]:
del model 
model = BartForConditionalGeneration(config)

In [13]:
from transformers import BartModel, BartForConditionalGeneration, BartConfig,BartTokenizer
import torch 

In [57]:
tokenizer = BartTokenizer.from_pretrained("facebook/bart-base")

In [54]:
tokenizer.prepare_seq2seq_batch(['I am fine Ansari', 'Are you okay ?'])

{'input_ids': [[0, 100, 524, 2051, 16866, 1512, 2], [0, 13755, 47, 8578, 17487, 2, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 0]]}

In [19]:
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state

In [163]:
config = {'_name_or_path': 'facebook/bart-large-cnn', '_num_labels': 3, 'activation_dropout': 0.0, 'activation_function': 'gelu', 'add_final_layer_norm': False, 'architectures': ['BartForConditionalGeneration'], 'attention_dropout': 0.0, 'bos_token_id': 0, 'classif_dropout': 0.0, 'classifier_dropout': 0.0, 'd_model': 1024, 'decoder_attention_heads': 16, 'decoder_ffn_dim': 4096, 'decoder_layerdrop': 0.0, 'decoder_layers': 12, 'decoder_start_token_id': 2, 'dropout': 0.1, 'early_stopping': True, 'encoder_attention_heads': 16, 'encoder_ffn_dim': 4096, 'encoder_layerdrop': 0.0, 'encoder_layers': 12, 'eos_token_id': 2, 'force_bos_token_to_be_generated': True, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2, 'gradient_checkpointing': False, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1', '2': 'LABEL_2'}, 'init_std': 0.02, 'is_encoder_decoder': True, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1, 'LABEL_2': 2}, 'length_penalty': 2.0, 'max_length': 142, 'max_position_embeddings': 1024, 'min_length': 56, 'model_type': 'bart', 'no_repeat_ngram_size': 3, 'normalize_before': False, 'num_beams': 4, 'num_hidden_layers': 12, 'output_past': True, 'pad_token_id': 1, 'prefix': ' ', 'scale_embedding': False, 'task_specific_params': {'summarization': {'early_stopping': True, 'length_penalty': 2.0, 'max_length': 142, 'min_length': 56, 'no_repeat_ngram_size': 3, 'num_beams': 4}}, 'transformers_version': '4.2.2', 'use_cache': True, 'vocab_size': 50264}
config = BartConfig(config)

In [95]:
import transformers
transformers.__file__

'/home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/site-packages/transformers/__init__.py'

In [ ]:
from transformers import BartTokenizer, BartForConditionalGeneration

# model = BartForConditionalGeneration.from_pretrained("facebook/bart-large-cnn")
# model = BartForConditionalGeneration(config)
model = BartForConditionalGeneration.from_pretrained("facebook/bart-large-cnn")

In [491]:
tokenizer.decode([0,1,2,3])

'<s><pad></s><unk>'

In [488]:
ARTICLE_TO_SUMMARIZE = (
    "PG&E stated it scheduled the blackouts in response to forecasts for high winds "
    "amid dry conditions. The aim is to reduce the risk of wildfires. Nearly 800 thousand customers were "
    "scheduled to be affected by the shutoffs which were expected to last through at least midday tomorrow."
)
inputs = tokenizer([ARTICLE_TO_SUMMARIZE], max_length=1024, return_tensors="pt")
inputs

{'input_ids': tensor([[    0,  8332,   947,   717,  2305,    24,  1768,     5,   909,  4518,
            11,  1263,     7,  5876,    13,   239,  2372,  2876,  3841,  1274,
             4,    20,  4374,    16,     7,  1888,     5,   810,     9, 12584,
             4,  9221,  5735,  7673,   916,    58,  1768,     7,    28,  2132,
            30,     5,  2572, 10816,    61,    58,   421,     7,    94,   149,
            23,   513, 15372,  3859,     4,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}

In [572]:
sent = "Today I am sad."
tokenizer.encode(sent), tokenizer.call(sent)

AttributeError: 'BartTokenizer' object has no attribute 'call'

In [ ]:
input_encodings = tokenizer.batch_encode_plus(example_batch['text'], pad_to_max_length=True, max_length=1024, truncation=True))

In [178]:
INPUT_IDS = torch.cat((inputs["input_ids"],inputs["input_ids"]), axis=0)
ATTN_MASK = torch.cat((inputs["attention_mask"],inputs["attention_mask"]), axis=0)
LABELS = torch.cat((labels,labels), axis=0)

In [239]:
summary_ids = model.generate(inputs["input_ids"], num_beams=2, min_length=0, max_length=20)

In [240]:
summary_ids

tensor([[   2,    0, 8332,  947,  717, 1768,    5,  909, 4518,   11, 1263,    7,
         5876,   13,  239, 2372, 2876, 3841, 1274,    2]])

In [72]:
tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

' Slam Slam Slam geared geared Vox Voxgren Slam Slam recurrent recurrent geared geared geared Maver Maver'

In [468]:
model.eval()
out = model(input_ids = inputs["input_ids"],attention_mask = inputs["attention_mask"], labels = inputs["input_ids"])
out.loss

tensor(10.8940, grad_fn=<NllLossBackward>)

In [429]:
inputs["input_ids"]

tensor([[    0,  8332,   947,   717,  2305,    24,  1768,     5,   909,  4518,
            11,  1263,     7,  5876,    13,   239,  2372,  2876,  3841,  1274,
             4,    20,  4374,    16,     7,  1888,     5,   810,     9, 12584,
             4,  9221,  5735,  7673,   916,    58,  1768,     7,    28,  2132,
            30,     5,  2572, 10816,    61,    58,   421,     7,    94,   149,
            23,   513, 15372,  3859,     4,     2]])

In [406]:
labuls = torch.tensor([[1]*56]).long()

In [418]:
labels = torch.argmax(out.logits, axis=2)
labels

tensor([[ 8332,  8332,   947,   717,  1768,    24,  1768,     5,   909,  4518,
            11,  1263,     7,  5876,    13,   239,  2372,  2876,  3841,  1274,
             4,  9221,  4374,    16,     7,  1888,     5,   810,     9, 12584,
             4,  9221,  5735,  7673,   916,    58,  1768,     7,    28,  2132,
            30,     5,  2572, 10816,     4,    58,   421,     7,    94,   149,
            23,   513, 15372,  3859,     4,     2]])

In [404]:
labels

tensor([[8332,  811,   20, 5735, 3913, 1768,  916, 2572, 4518,   32,   20,    7,
         5876, 2372,   20, 2372,    4,   20, 1274,    4]])

In [377]:
v,idx = torch.topk((out.logits), k=1,axis=2)
v,idx

(tensor([[[11.8544],
          [11.0273],
          [10.9150],
          [13.9413],
          [10.4414],
          [11.5450],
          [ 8.8487],
          [12.5335],
          [11.4360],
          [11.8563],
          [11.5445],
          [12.6755],
          [11.8272],
          [14.3440],
          [10.5630],
          [14.0671],
          [12.2241],
          [11.3962],
          [13.3064],
          [12.6422]]], grad_fn=<TopkBackward>),
 tensor([[[8332],
          [ 811],
          [  20],
          [5735],
          [3913],
          [1768],
          [ 916],
          [2572],
          [4518],
          [  32],
          [  20],
          [   7],
          [5876],
          [2372],
          [  20],
          [2372],
          [   4],
          [  20],
          [1274],
          [   4]]]))

In [402]:
labels = idx.squeeze(2)

In [156]:
inpuT = torch.tensor([[.1,.7,.1,.1]]).float()
target = torch.tensor([1]).long()
output = loss_fct(inpuT, target)
inpuT, target, output

(tensor([[0.1000, 0.7000, 0.1000, 0.1000]]), tensor([1]), tensor(0.9732))

In [212]:
from torch.nn.functional import log_softmax
log_softmax(torch.tensor([[.1,.7,.1,.1]]).float())

/tmp/ipykernel_152702/2635051294.py:2: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  log_softmax(torch.tensor([[.1,.7,.1,.1]]).float())


tensor([[-1.5732, -0.9732, -1.5732, -1.5732]])

In [91]:
labels = torch.tensor([[    0,  8332,   947,   717,  2305,    24,  1768,     5,   909,  4518,
            11,  1263,     7,  5876,    13,   239,  2372,  2876,  3841,  1274,
             4,    20,  4374,    16,     7,  1888,     5,   810,     9, 12584,
             4,  9221,  5735,  7673,   916,    58,  1768,     7,    28,  2132,
            30,     5,  2572, 10816,    61,    58,   421,     7,    94,   149,
            23,   513, 15372,  3859,     4,     2]])

In [ ]:
from transformers import BartTokenizer
tokenizer = BartTokenizer.from_pretrained("facebook/bart-large-cnn")

In [ ]:
summary_ids = model.generate(article_input_ids,num_beams=4,length_penalty=2.0,max_length=142)

In [61]:
from IPython.display import display, Markdown

In [74]:
summary_txt = tokenizer.decode(torch.tensor([[    2,     0, 12133, 23334, 23334, 23334, 29247, 29247, 29247, 12113,
         12113, 12113, 24235, 24235, 47927, 47927, 47927, 24235, 24235,     2]]), skip_special_tokens=True)

NameError: name 'tokenizer' is not defined

# Mask filling

In [255]:
TXT = "My friends are <mask> but they eat too many carbs."
input_ids = tokenizer([TXT], return_tensors="pt")["input_ids"]


In [258]:
help(model.generate)

Help on method generate in module transformers.generation_utils:

generate(input_ids: Union[torch.LongTensor, NoneType] = None, max_length: Union[int, NoneType] = None, min_length: Union[int, NoneType] = None, do_sample: Union[bool, NoneType] = None, early_stopping: Union[bool, NoneType] = None, num_beams: Union[int, NoneType] = None, temperature: Union[float, NoneType] = None, top_k: Union[int, NoneType] = None, top_p: Union[float, NoneType] = None, repetition_penalty: Union[float, NoneType] = None, bad_words_ids: Union[Iterable[int], NoneType] = None, bos_token_id: Union[int, NoneType] = None, pad_token_id: Union[int, NoneType] = None, eos_token_id: Union[int, NoneType] = None, length_penalty: Union[float, NoneType] = None, no_repeat_ngram_size: Union[int, NoneType] = None, num_return_sequences: Union[int, NoneType] = None, decoder_start_token_id: Union[int, NoneType] = None, use_cache: Union[bool, NoneType] = None, num_beam_groups: Union[int, NoneType] = None, diversity_penalty: Uni

In [256]:
out = model(input_ids).logits
logits = out.logits


IndexError: index out of range in self

In [ ]:
masked_index = (input_ids[0] == tokenizer.mask_token_id).nonzero().item()
probs = logits[0, masked_index].softmax(dim=0)
values, predictions = probs.topk(5)

tokenizer.decode(predictions).split()

# Decoder input ids and attention

In [529]:
from transformers.models.bart.modeling_bart import shift_tokens_right, _make_causal_mask, _expand_mask

In [573]:
input_ids = torch.tensor([[1,4,5,6,7,2], [1,4,5,2,0,0]])
output_ids = torch.tensor([[4,4,5,5,6,6,7,7,2], [4,4,5,5,2,0,0,0,0]])

In [575]:
help(shift_tokens_right)

Help on function shift_tokens_right in module transformers.models.bart.modeling_bart:

shift_tokens_right(input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int)
    Shift input ids one token to the right.



In [569]:
cm = _make_causal_mask(output_ids.size(), input_ids.dtype)
cmm = cm.clone()
cmm[cm == -9223372036854775808] = 1
cmm

tensor([[[[0, 1, 1, 1, 1, 1, 1, 1, 1],
          [0, 0, 1, 1, 1, 1, 1, 1, 1],
          [0, 0, 0, 1, 1, 1, 1, 1, 1],
          [0, 0, 0, 0, 1, 1, 1, 1, 1],
          [0, 0, 0, 0, 0, 1, 1, 1, 1],
          [0, 0, 0, 0, 0, 0, 1, 1, 1],
          [0, 0, 0, 0, 0, 0, 0, 1, 1],
          [0, 0, 0, 0, 0, 0, 0, 0, 1],
          [0, 0, 0, 0, 0, 0, 0, 0, 0]]],


        [[[0, 1, 1, 1, 1, 1, 1, 1, 1],
          [0, 0, 1, 1, 1, 1, 1, 1, 1],
          [0, 0, 0, 1, 1, 1, 1, 1, 1],
          [0, 0, 0, 0, 1, 1, 1, 1, 1],
          [0, 0, 0, 0, 0, 1, 1, 1, 1],
          [0, 0, 0, 0, 0, 0, 1, 1, 1],
          [0, 0, 0, 0, 0, 0, 0, 1, 1],
          [0, 0, 0, 0, 0, 0, 0, 0, 1],
          [0, 0, 0, 0, 0, 0, 0, 0, 0]]]])

In [554]:
attention_mask = (input_ids!=0).long()
out_attention_mask = (output_ids!=0).long()
attention_mask,out_attention_mask

(tensor([[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 0]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]))

In [557]:
out = model(input_ids=input_ids, attention_mask = attention_mask, decoder_input_ids = output_ids, decoder_attention_mask = out_attention_mask)

In [563]:
out.logits.shape

torch.Size([2, 10, 200000])

In [556]:
output_ids.shape

torch.Size([2, 10])

In [503]:
input_ids.shape

torch.Size([2, 6])

# Loss niye khela kori 

In [166]:
from torch.nn import CrossEntropyLoss
loss_fct = CrossEntropyLoss()
softmax = torch.nn.Softmax()

In [284]:
model.config.vocab_size

50264

In [291]:
inpuT = torch.tensor([[11]+[1]*50263]*20).float()
target = torch.tensor([0]*20).long()
output = loss_fct((inpuT), target)
output2 = loss_fct(softmax(inpuT), target)
inpuT, softmax(inpuT),target, output,output2

/tmp/ipykernel_152702/1720163948.py:4: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output2 = loss_fct(softmax(inpuT), target)
/tmp/ipykernel_152702/1720163948.py:5: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  inpuT, softmax(inpuT),target, output,output2


(tensor([[11.,  1.,  1.,  ...,  1.,  1.,  1.],
         [11.,  1.,  1.,  ...,  1.,  1.,  1.],
         [11.,  1.,  1.,  ...,  1.,  1.,  1.],
         ...,
         [11.,  1.,  1.,  ...,  1.,  1.,  1.],
         [11.,  1.,  1.,  ...,  1.,  1.,  1.],
         [11.,  1.,  1.,  ...,  1.,  1.,  1.]]),
 tensor([[3.0469e-01, 1.3833e-05, 1.3833e-05,  ..., 1.3833e-05, 1.3833e-05,
          1.3833e-05],
         [3.0469e-01, 1.3833e-05, 1.3833e-05,  ..., 1.3833e-05, 1.3833e-05,
          1.3833e-05],
         [3.0469e-01, 1.3833e-05, 1.3833e-05,  ..., 1.3833e-05, 1.3833e-05,
          1.3833e-05],
         ...,
         [3.0469e-01, 1.3833e-05, 1.3833e-05,  ..., 1.3833e-05, 1.3833e-05,
          1.3833e-05],
         [3.0469e-01, 1.3833e-05, 1.3833e-05,  ..., 1.3833e-05, 1.3833e-05,
          1.3833e-05],
         [3.0469e-01, 1.3833e-05, 1.3833e-05,  ..., 1.3833e-05, 1.3833e-05,
          1.3833e-05]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor(1.1885),
 ten

In [217]:
softmax(inpuT)

/tmp/ipykernel_152702/1181773492.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax(inpuT)


tensor([[0.5000, 0.5000]])

In [224]:
sum(sum(inpuT))

tensor(1.)

In [272]:
math.log

<function math.log>

In [282]:
y = 1
a = 0.99999
(y*math.log(a)+(1-y)*math.log(1-a))*-1

1.0000050000287824e-05

In [304]:
means, stds = torch.mean(out.logits,axis=2),torch.std(out.logits,axis=2)

In [328]:
torch.tensor(11)

tensor(11)

In [356]:
logits2 = torch.stack([torch.normal(x.item(),y.item(),size=(1,model.config.vocab_size)) for x,y in zip(means[0,:], stds[0])])
logits2[:,0,0] = torch.tensor([11]*len(stds[0]))

In [358]:
logits2 = logits2.permute(1,0,2)
logits2 = logits2[0,:,:]
target = torch.tensor([0]*len(stds[0]))

In [359]:
logits2.shape

torch.Size([20, 50264])

In [360]:
output = loss_fct((logits2), target)
output2 = loss_fct(softmax(logits2), target)
logits2, softmax(logits2),target, output,output2

/tmp/ipykernel_152702/422661247.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output2 = loss_fct(softmax(logits2), target)
/tmp/ipykernel_152702/422661247.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  logits2, softmax(logits2),target, output,output2


(tensor([[ 1.1000e+01, -4.1907e-01,  1.7334e+00,  ..., -7.8270e-01,
           2.1868e+00,  2.6956e-02],
         [ 1.1000e+01,  3.0929e+00,  8.8143e-01,  ..., -9.4053e-01,
           4.9956e-03,  2.4194e+00],
         [ 1.1000e+01,  2.1822e-01,  2.2500e-01,  ..., -2.1329e+00,
           3.8443e-01, -1.4089e+00],
         ...,
         [ 1.1000e+01, -2.7124e+00, -4.0935e+00,  ...,  1.0854e+00,
          -6.6496e+00,  1.0127e+00],
         [ 1.1000e+01,  2.1054e-01, -2.6392e+00,  ...,  7.0419e-02,
          -1.0109e+00, -2.6814e+00],
         [ 1.1000e+01,  1.2023e+00,  4.3087e-01,  ...,  4.2815e-02,
          -3.3244e-01, -3.8566e-01]]),
 tensor([[2.6268e-01, 2.8853e-06, 2.4830e-05,  ..., 2.0057e-06, 3.9077e-05,
          4.5071e-06],
         [1.8109e-01, 6.6662e-05, 7.3020e-06,  ..., 1.1808e-06, 3.0396e-06,
          3.3993e-05],
         [3.5379e-01, 7.3498e-06, 7.3999e-06,  ..., 7.0020e-07, 8.6788e-06,
          1.4443e-06],
         ...,
         [4.1967e-01, 4.6524e-07, 1.1692e-0